name: Runner Inspection

on:
  workflow_dispatch:

jobs:
  inspect:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: System Info
        run: |
          uname -a
          whoami
          pwd
          ls -la